### ISSUE TITLE
Reverted buttons?

### ISSUE THREAD

**Issue by mrmajik45** [victorqribeiro/invaderz#11]
Did someone Revert my Button PR?

**Comment by mrmajik45** [comment]
No. Someone broke the sw.js file

**Comment by victorqribeiro** [comment]
What do you mean?

**Comment by mrmajik45** [comment]
Your website seems to show the old css. I cleared cache but it still has the old css.

**Comment by mrmajik45** [comment]
Yep. Downloading the repo and running it has the new CSS.
