### ISSUE TITLE
Zoom on Ipad Pro in Safari

### ISSUE THREAD

**Issue by GesaP** [victorqribeiro/invaderz#13]
Hey there, 
the soon as I start playing the game on the live version,
I get zoomed in, and can‘t see the upper halve of the game anymore.
Know any way this could be fixed?
Cool idea, btw!

**Comment by victorqribeiro** [comment]
clear the cache and try again, please

**Comment by GesaP** [comment]
still starting to zoom in when clicking any button. Buttons look nicer now though...

**Comment by SoffiMeower** [comment]
(You're welcome for the buttons)

**Comment by victorqribeiro** [comment]
I can't seem to reproduce this behavior so I can figure it out how to solve it. is it only happening on iPad?

**Comment by GesaP** [comment]
Actually, no. Same behaviour on iPhone and with Chrome.
