### ISSUE TITLE
Demo is not opening

### ISSUE THREAD

**Issue by bauripalash** [victorqribeiro/invaderz#3]
I tried opening the mentioned link of the demo. But it didn't open and showed an error, Site cannot be reached

**Comment by pSub** [comment]
The demo at https://victorribeiro.com/invaderz/ works for me. Do you have Javascript enabled?

**Comment by victorqribeiro** [comment]
> I tried opening the mentioned link of the demo. But it didn't open and showed an error, Site cannot be reached

Maybe the servers went down when you tried to access it. Besides that, you can always clone the repo and run it locally, have you tried that?

**Comment by bauripalash** [comment]
### Something is Wrong
Though I was able to run it locally. 
Still i was curious and tried opening the site via a web proxy , <https://proxysite.com> and Selected EU 
server and it opened instantly. But if I try running it without any proxy it won't load. I tried every possible browser in different different computers, laptops , mobiles .
I think there is some kind of geological blocking or something like that.

**Comment by victorqribeiro** [comment]
Never heard nothing like that. Is your ISP blocking some sites? Where are you in the world?

**Comment by bauripalash** [comment]
I'm from West Bengal, India

**Comment by victorqribeiro** [comment]
Can you tell me your IP so I can check?

**Comment by victorqribeiro** [comment]
https://victorqribeiro.github.io/invaderz
