### ISSUE TITLE
Live version is down (again)

### ISSUE THREAD

**Issue by ctrlcctrlv** [victorqribeiro/invaderz#4]

**Comment by victorqribeiro** [comment]
I have to further investigate this. Here is fine. What is your location?

**Comment by ctrlcctrlv** [comment]
Why was my issue closed? Your domain is clearly misconfigured.

```
[fred@pc ~]$ dig A victorribeiro.com @1.1.1.1

; <<>> DiG 9.13.3 <<>> A victorribeiro.com @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 12073
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;victorribeiro.com.             IN      A

;; Query time: 4246 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri Nov 09 12:41:38 PST 2018
;; MSG SIZE  rcvd: 46
```

![borked](https://user-images.githubusercontent.com/838783/48243761-f1198980-e41c-11e8-9c63-4577ede1ab6f.png)

Do you think I'm lying or something?

**Comment by victorqribeiro** [comment]
No, I don't think you're lying, you just didn't answer my question 9 hours after I asked. I will forward this to my hosting service and see what they can do about it. Could you please tell me your location? A guy in India claimed he has a similar issue.

**Comment by ctrlcctrlv** [comment]
Philippines. Sorry, I was sleeping. I live in GMT+8

**Comment by victorqribeiro** [comment]
That's ok. I'll sleep now, tomorrow I'll ask my hosting service to take a look. If you have a idea what's wrong feel free to tell me.

**Comment by ctrlcctrlv** [comment]
I believe your GoDaddy account is misconfigured. Their nameservers aren't returning a valid IP, so then DNS providers are getting stuck with an empty A record.

**Comment by victorqribeiro** [comment]
I have opened a issue with go daddy and with the hosting services - they are not the same; I'll see what they say about it.

**Comment by victorqribeiro** [comment]
My hosting service just answered and told me there is a region block due to an attack that's going on. They told me as soon the wave of attacks end they will unblock.

**Comment by victorqribeiro** [comment]
https://victorqribeiro.github.io/invaderz
